/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author itzel
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnIniciarSesion1 = new javax.swing.JButton();
        btnIniciarSesion2 = new javax.swing.JButton();
        btnIniciarSesion3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(92, 153, 135));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Abarrotes Arely");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(0, 229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 230, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion.setText("Categorías");
        btnIniciarSesion.setToolTipText("");
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion.setRequestFocusEnabled(false);
        btnIniciarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión2.png"))); // NOI18N
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion1.setText("Realizar Venta");
        btnIniciarSesion1.setToolTipText("");
        btnIniciarSesion1.setBorderPainted(false);
        btnIniciarSesion1.setContentAreaFilled(false);
        btnIniciarSesion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion1.setRequestFocusEnabled(false);
        btnIniciarSesion1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión2.png"))); // NOI18N
        btnIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion1ActionPerformed(evt);
            }
        });

        btnIniciarSesion2.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnSalir.png"))); // NOI18N
        btnIniciarSesion2.setText("Cerrar Sesión");
        btnIniciarSesion2.setToolTipText("");
        btnIniciarSesion2.setBorderPainted(false);
        btnIniciarSesion2.setContentAreaFilled(false);
        btnIniciarSesion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnSalir.png"))); // NOI18N
        btnIniciarSesion2.setRequestFocusEnabled(false);
        btnIniciarSesion2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnSalirSelected.png"))); // NOI18N
        btnIniciarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion2ActionPerformed(evt);
            }
        });

        btnIniciarSesion3.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion3.setText("Productos");
        btnIniciarSesion3.setToolTipText("");
        btnIniciarSesion3.setBorderPainted(false);
        btnIniciarSesion3.setContentAreaFilled(false);
        btnIniciarSesion3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarSesion3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión1.png"))); // NOI18N
        btnIniciarSesion3.setRequestFocusEnabled(false);
        btnIniciarSesion3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/imagenes/btnIniciarSesión2.png"))); // NOI18N
        btnIniciarSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciarSesion1)
                    .addComponent(btnIniciarSesion3)
                    .addComponent(btnIniciarSesion2)
                    .addComponent(btnIniciarSesion))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnIniciarSesion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion3)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion2)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion1ActionPerformed

    private void btnIniciarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion2ActionPerformed

    private void btnIniciarSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JButton btnIniciarSesion2;
    private javax.swing.JButton btnIniciarSesion3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
